version: '3'

services:
  mysql57:
    image: mysql:5.7
    container_name: mysql_57
    # restart: unless-stopped
    # tty: true
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
    volumes:
        - ./my.cnf:/etc/my.cnf
        - ./init.sql:/data/application/init.sql
    command: --default-authentication-plugin=mysql_native_password --init-file=/data/application/init.sql

#Docker Networks
networks:
  default:
    external:
      name: nginx-proxy
